TOP=../..
include $(TOP)/configure/CONFIG

# Install databases, templates & substitutions like this
DB += watchdog.vdb
DB += simservices_acr.vdb
#DB_INSTALLS += $(ASYN)/db/asynRecord.db
DB_INSTALLS += $(IOCADMIN)/db/iocAdminSoft.db

include $(TOP)/configure/RULES


