/* C code for program scanProgress, generated by snc from ../scanProg.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 31 "../scanProg.st"
#include <string.h>
# line 32 "../scanProg.st"
#include <epicsThread.h>
# line 33 "../scanProg.st"
#include <epicsTime.h>
# line 34 "../scanProg.st"
#include <string.h>
# line 35 "../scanProg.st"
#include <time.h>
# line 54 "../scanProg.st"
static const EF_ID scanProgressDebug_mon = 1;
# line 80 "../scanProg.st"
static const EF_ID pause1_mon = 2;
# line 81 "../scanProg.st"
static const EF_ID pause2_mon = 3;
# line 82 "../scanProg.st"
static const EF_ID pause3_mon = 4;
# line 83 "../scanProg.st"
static const EF_ID pause4_mon = 5;
# line 84 "../scanProg.st"
static const EF_ID busy1_mon = 6;
# line 85 "../scanProg.st"
static const EF_ID busy2_mon = 7;
# line 86 "../scanProg.st"
static const EF_ID busy3_mon = 8;
# line 87 "../scanProg.st"
static const EF_ID busy4_mon = 9;
# line 106 "../scanProg.st"
static void clocks2str(long isec, char *str);
# line 107 "../scanProg.st"
static void formatTimeStr(char *tStr, int tStrLen, long final, int full);
# line 108 "../scanProg.st"
static long calc_cpt(void);
# line 109 "../scanProg.st"
static int allStopped(void);

/* Variable declarations */
# line 54 "../scanProg.st"
static	short scanProgressDebug;
# line 55 "../scanProg.st"
static	double fractionDone;
# line 56 "../scanProg.st"
static	double percentDone;
# line 57 "../scanProg.st"
static	string startingTimeStr;
# line 58 "../scanProg.st"
static	string endingTimeStr;
# line 59 "../scanProg.st"
static	string remainingTimeStr;
# line 60 "../scanProg.st"
static	string pauseTimeStr;
# line 61 "../scanProg.st"
static	string totalElapsedTimeStr;
# line 62 "../scanProg.st"
static	string totalActiveTimeStr;
# line 63 "../scanProg.st"
static	int pauseSec;
# line 64 "../scanProg.st"
static	int remainingSec;
# line 65 "../scanProg.st"
static	int npts;
# line 66 "../scanProg.st"
static	int cpt;
# line 67 "../scanProg.st"
static	short running;
# line 68 "../scanProg.st"
static	short paused;
# line 69 "../scanProg.st"
static	int Npauses;
# line 70 "../scanProg.st"
static	double version;
# line 72 "../scanProg.st"
static	int npts1;
# line 73 "../scanProg.st"
static	int npts2;
# line 74 "../scanProg.st"
static	int npts3;
# line 75 "../scanProg.st"
static	int npts4;
# line 76 "../scanProg.st"
static	int cpt1;
# line 77 "../scanProg.st"
static	int cpt2;
# line 78 "../scanProg.st"
static	int cpt3;
# line 79 "../scanProg.st"
static	int cpt4;
# line 80 "../scanProg.st"
static	short pause1;
# line 81 "../scanProg.st"
static	short pause2;
# line 82 "../scanProg.st"
static	short pause3;
# line 83 "../scanProg.st"
static	short pause4;
# line 84 "../scanProg.st"
static	short busy1;
# line 85 "../scanProg.st"
static	short busy2;
# line 86 "../scanProg.st"
static	short busy3;
# line 87 "../scanProg.st"
static	short busy4;
# line 90 "../scanProg.st"
static	char *SNLtaskName;
# line 91 "../scanProg.st"
static	char new_msg[256];
# line 94 "../scanProg.st"
static	long predictEnd;
# line 95 "../scanProg.st"
static	long startTime;
# line 96 "../scanProg.st"
static	long pauseStart;
# line 97 "../scanProg.st"
static	long now;
# line 98 "../scanProg.st"
static	char tStr[100];
# line 99 "../scanProg.st"
static	char tStr1[100];
# line 100 "../scanProg.st"
static	int beginPause;
# line 101 "../scanProg.st"
static	int almostPaused;
# line 102 "../scanProg.st"
static	int stopped;
# line 103 "../scanProg.st"
static	int aPause;
# line 104 "../scanProg.st"
static	int scanDim;


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "scanProgress" ******/

/* Event function for state "init" in state set "scanProgress" */
static seqBool seqg_event_scanProgress_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "scanProgress" */
static void seqg_action_scanProgress_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 118 "../scanProg.st"
			SNLtaskName = seq_macValueGet(seqg_env, "name");
# line 119 "../scanProg.st"
			scanDim = 1;
# line 120 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 0/*scanProgressDebug*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 121 "../scanProg.st"
				version = (2.1);
# line 121 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 16/*version*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 122 "../scanProg.st"
				fractionDone = (0.0);
# line 122 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 1/*fractionDone*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 123 "../scanProg.st"
				percentDone = (0.0);
# line 123 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 2/*percentDone*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 124 "../scanProg.st"
				strcpy(endingTimeStr, "");
# line 124 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 4/*endingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 124 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 125 "../scanProg.st"
				strcpy(remainingTimeStr, "");
# line 125 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 5/*remainingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 125 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 126 "../scanProg.st"
				strcpy(pauseTimeStr, "");
# line 126 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 6/*pauseTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 126 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 127 "../scanProg.st"
				strcpy(startingTimeStr, "");
# line 127 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 3/*startingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 127 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 128 "../scanProg.st"
				strcpy(totalElapsedTimeStr, "");
# line 128 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 128 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 129 "../scanProg.st"
				strcpy(totalActiveTimeStr, "");
# line 129 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 8/*totalActiveTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 129 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 130 "../scanProg.st"
				pauseSec = (0);
# line 130 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 9/*pauseSec*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 131 "../scanProg.st"
				remainingSec = (0);
# line 131 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 10/*remainingSec*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 132 "../scanProg.st"
				npts = (0);
# line 132 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 11/*npts*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 133 "../scanProg.st"
				cpt = (0);
# line 133 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 12/*cpt*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 134 "../scanProg.st"
				Npauses = (0);
# line 134 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 15/*Npauses*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 135 "../scanProg.st"
				running = (0);
# line 135 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 13/*running*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 136 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 29/*busy1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 137 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 30/*busy2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 138 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 31/*busy3*/, DEFAULT, DEFAULT_TIMEOUT);
# line 139 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 32/*busy4*/, DEFAULT, DEFAULT_TIMEOUT);
# line 140 "../scanProg.st"
			beginPause = 0;
# line 141 "../scanProg.st"
			seq_efClear(seqg_env, scanProgressDebug_mon);
# line 142 "../scanProg.st"
			if (scanProgressDebug >= 1)
			{
# line 142 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 142, SNLtaskName, 1);
# line 142 "../scanProg.st"
				;
# line 142 "../scanProg.st"
				printf("%s\n", "init complete in state init");
# line 142 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 142 "../scanProg.st"
			;
		}
		return;
	}
}

/****** Code for state "idle" in state set "scanProgress" ******/

/* Event function for state "idle" in state set "scanProgress" */
static seqBool seqg_event_scanProgress_0_idle(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 148 "../scanProg.st"
	if (seq_efTest(seqg_env, scanProgressDebug_mon))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 154 "../scanProg.st"
	if (busy1 || busy2 || busy3 || busy4)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idle" in state set "scanProgress" */
static void seqg_action_scanProgress_0_idle(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 149 "../scanProg.st"
			sprintf(new_msg, "changed debug flag to %d", scanProgressDebug);
# line 150 "../scanProg.st"
			if (scanProgressDebug >= 1)
			{
# line 150 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 150, SNLtaskName, 1);
# line 150 "../scanProg.st"
				;
# line 150 "../scanProg.st"
				printf("%s\n", new_msg);
# line 150 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 150 "../scanProg.st"
			;
# line 151 "../scanProg.st"
			seq_efClear(seqg_env, scanProgressDebug_mon);
		}
		return;
	case 1:
		{
# line 155 "../scanProg.st"
			if (scanProgressDebug >= 1)
			{
# line 155 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 155, SNLtaskName, 1);
# line 155 "../scanProg.st"
				;
# line 155 "../scanProg.st"
				printf("%s\n", "scan started");
# line 155 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 155 "../scanProg.st"
			;
# line 156 "../scanProg.st"
			if (busy4)
# line 156 "../scanProg.st"
				scanDim = 4;
			else
# line 157 "../scanProg.st"
				if (busy3)
# line 157 "../scanProg.st"
					scanDim = 3;
				else
# line 158 "../scanProg.st"
					if (busy2)
# line 158 "../scanProg.st"
						scanDim = 2;
					else
# line 159 "../scanProg.st"
						scanDim = 1;
# line 160 "../scanProg.st"
			sprintf(new_msg, "got scanDim = %d", scanDim);
# line 161 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 161 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 161, SNLtaskName, 2);
# line 161 "../scanProg.st"
				;
# line 161 "../scanProg.st"
				printf("%s\n", new_msg);
# line 161 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 161 "../scanProg.st"
			;
			startTime = time(0L);
			formatTimeStr(startingTimeStr,40,startTime,1);
# line 164 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 3/*startingTimeStr*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 165 "../scanProg.st"
				Npauses = (0);
# line 165 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 15/*Npauses*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 166 "../scanProg.st"
				pauseSec = (0);
# line 166 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 9/*pauseSec*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 167 "../scanProg.st"
				fractionDone = (0.0);
# line 167 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 1/*fractionDone*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 168 "../scanProg.st"
				percentDone = (0.0);
# line 168 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 2/*percentDone*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 169 "../scanProg.st"
				running = (1);
# line 169 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 13/*running*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 170 "../scanProg.st"
				strcpy(totalElapsedTimeStr, "00:00:00");
# line 170 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 170 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 171 "../scanProg.st"
				strcpy(totalActiveTimeStr, "00:00:00");
# line 171 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 8/*totalActiveTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 171 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			{
# line 172 "../scanProg.st"
				strcpy(pauseTimeStr, "00:00:00");
# line 172 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 6/*pauseTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 172 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 173 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 17/*npts1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 174 "../scanProg.st"
			npts = npts1;
# line 175 "../scanProg.st"
			if (scanDim >= 2)
			{
# line 176 "../scanProg.st"
				seq_pvGetTmo(seqg_env, 18/*npts2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 177 "../scanProg.st"
				npts *= npts2;
# line 178 "../scanProg.st"
				if (scanDim >= 3)
				{
# line 179 "../scanProg.st"
					seq_pvGetTmo(seqg_env, 19/*npts3*/, DEFAULT, DEFAULT_TIMEOUT);
# line 180 "../scanProg.st"
					npts *= npts3;
# line 181 "../scanProg.st"
					if (scanDim >= 4)
					{
# line 182 "../scanProg.st"
						seq_pvGetTmo(seqg_env, 20/*npts4*/, DEFAULT, DEFAULT_TIMEOUT);
# line 183 "../scanProg.st"
						npts *= npts4;
					}
				}
			}
# line 187 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 11/*npts*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "duringScan" in state set "scanProgress" ******/

/* Event function for state "duringScan" in state set "scanProgress" */
static seqBool seqg_event_scanProgress_0_duringScan(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 194 "../scanProg.st"
	if (!(busy1 || busy2 || busy3 || busy4))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 198 "../scanProg.st"
	if (paused)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 203 "../scanProg.st"
	if (seq_delay(seqg_env, 2.))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "duringScan" in state set "scanProgress" */
static void seqg_action_scanProgress_0_duringScan(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 195 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 195 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 195, SNLtaskName, 2);
# line 195 "../scanProg.st"
				;
# line 195 "../scanProg.st"
				printf("%s\n", "in duringScan, scan is done, goto scanFinish");
# line 195 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 195 "../scanProg.st"
			;
		}
		return;
	case 1:
		{
# line 199 "../scanProg.st"
			beginPause = 1;
# line 200 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 200 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 200, SNLtaskName, 2);
# line 200 "../scanProg.st"
				;
# line 200 "../scanProg.st"
				printf("%s\n", "in duringScan, scan is paused, goto duringScanPause");
# line 200 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 200 "../scanProg.st"
			;
		}
		return;
	case 2:
		{
# line 204 "../scanProg.st"
			if (scanProgressDebug >= 3)
			{
# line 204 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 204, SNLtaskName, 3);
# line 204 "../scanProg.st"
				;
# line 204 "../scanProg.st"
				printf("%s\n", "in duringScan, do a regular update to progress");
# line 204 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 204 "../scanProg.st"
			;
# line 205 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 21/*cpt1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 206 "../scanProg.st"
			if (scanDim >= 2)
			{
# line 207 "../scanProg.st"
				seq_pvGetTmo(seqg_env, 22/*cpt2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 208 "../scanProg.st"
				if (scanDim >= 3)
				{
# line 209 "../scanProg.st"
					seq_pvGetTmo(seqg_env, 23/*cpt3*/, DEFAULT, DEFAULT_TIMEOUT);
# line 210 "../scanProg.st"
					if (scanDim >= 4)
					{
# line 211 "../scanProg.st"
						seq_pvGetTmo(seqg_env, 24/*cpt4*/, DEFAULT, DEFAULT_TIMEOUT);
					}
				}
			}
# line 215 "../scanProg.st"
			cpt = calc_cpt();
# line 216 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 12/*cpt*/, DEFAULT, DEFAULT_TIMEOUT);
			fractionDone = (double)cpt/(double)npts;
# line 218 "../scanProg.st"
			sprintf(new_msg, "scanDim = %d,  completed = {%d/%d,  %d/%d,  %d/%d,  %d/%d}, fractionDone = %g", scanDim, cpt1, npts1, cpt2, npts2, cpt3, npts3, cpt4, npts4, fractionDone);
# line 219 "../scanProg.st"
			if (scanProgressDebug >= 4)
			{
# line 219 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 219, SNLtaskName, 4);
# line 219 "../scanProg.st"
				;
# line 219 "../scanProg.st"
				printf("%s\n", new_msg);
# line 219 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 219 "../scanProg.st"
			;
# line 220 "../scanProg.st"
			if (fractionDone > 1.0)
# line 220 "../scanProg.st"
				fractionDone = 1.0;
			else
# line 221 "../scanProg.st"
				if (fractionDone <= 0.0)
# line 221 "../scanProg.st"
					fractionDone = 0.0;
# line 222 "../scanProg.st"
			if (fractionDone > 0.0)
			{
				/* C code definitions */
# line 223 "../scanProg.st"
				now = time(0L);
# line 224 "../scanProg.st"
				remainingSec = (1.0-fractionDone)/fractionDone * (double)(now-startTime-pauseSec);
# line 225 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 10/*remainingSec*/, DEFAULT, DEFAULT_TIMEOUT);
# line 226 "../scanProg.st"
				predictEnd = now + remainingSec;
				clocks2str(remainingSec,tStr);
				{
# line 228 "../scanProg.st"
					strcpy(remainingTimeStr, tStr);
# line 228 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 5/*remainingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 228 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				clocks2str(now-startTime,tStr);
				{
# line 230 "../scanProg.st"
					strcpy(totalElapsedTimeStr, tStr);
# line 230 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 230 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				clocks2str(now-startTime-pauseSec,tStr);
				{
# line 232 "../scanProg.st"
					strcpy(totalActiveTimeStr, tStr);
# line 232 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 8/*totalActiveTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 232 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				formatTimeStr(endingTimeStr,40,predictEnd,0);
# line 234 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 4/*endingTimeStr*/, DEFAULT, DEFAULT_TIMEOUT);
# line 235 "../scanProg.st"
				sprintf(new_msg, "   now = %ld sec,   remaining = %d,  predictEnd = %ld", now, remainingSec, predictEnd);
# line 236 "../scanProg.st"
				if (scanProgressDebug >= 5)
				{
# line 236 "../scanProg.st"
					printf("<%s,%d,%s,%d> ", "../scanProg.st", 236, SNLtaskName, 5);
# line 236 "../scanProg.st"
					;
# line 236 "../scanProg.st"
					printf("%s\n", new_msg);
# line 236 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
# line 236 "../scanProg.st"
				;
# line 237 "../scanProg.st"
				sprintf(new_msg, "   remainingTimeStr = '%s',   endingTimeStr = '%s'", remainingTimeStr, endingTimeStr);
# line 238 "../scanProg.st"
				if (scanProgressDebug >= 5)
				{
# line 238 "../scanProg.st"
					printf("<%s,%d,%s,%d> ", "../scanProg.st", 238, SNLtaskName, 5);
# line 238 "../scanProg.st"
					;
# line 238 "../scanProg.st"
					printf("%s\n", new_msg);
# line 238 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
# line 238 "../scanProg.st"
				;
			}
			else
			{
				{
# line 241 "../scanProg.st"
					strcpy(remainingTimeStr, "");
# line 241 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 5/*remainingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 241 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				{
# line 242 "../scanProg.st"
					strcpy(totalActiveTimeStr, "");
# line 242 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 8/*totalActiveTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 242 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				{
# line 243 "../scanProg.st"
					strcpy(endingTimeStr, "");
# line 243 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 4/*endingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 243 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				{
# line 244 "../scanProg.st"
					strcpy(totalElapsedTimeStr, "");
# line 244 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 244 "../scanProg.st"
					epicsThreadSleep(0.01);
				}
				{
# line 245 "../scanProg.st"
					remainingSec = (0);
# line 245 "../scanProg.st"
					seq_pvPutTmo(seqg_env, 10/*remainingSec*/, SYNC, DEFAULT_TIMEOUT);
				}
			}
# line 247 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 1/*fractionDone*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 248 "../scanProg.st"
				percentDone = (100.0 * fractionDone);
# line 248 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 2/*percentDone*/, SYNC, DEFAULT_TIMEOUT);
			}
		}
		return;
	}
}

/****** Code for state "duringScanPause" in state set "scanProgress" ******/

/* Event function for state "duringScanPause" in state set "scanProgress" */
static seqBool seqg_event_scanProgress_0_duringScanPause(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 254 "../scanProg.st"
	if (!(busy1 || busy2 || busy3 || busy4))
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 258 "../scanProg.st"
	if (beginPause)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 265 "../scanProg.st"
	if (!paused)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 273 "../scanProg.st"
	if (seq_delay(seqg_env, 2.))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 3;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "duringScanPause" in state set "scanProgress" */
static void seqg_action_scanProgress_0_duringScanPause(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 255 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 255 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 255, SNLtaskName, 2);
# line 255 "../scanProg.st"
				;
# line 255 "../scanProg.st"
				printf("%s\n", "in duringScanPause, scan is done, goto scanFinish");
# line 255 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 255 "../scanProg.st"
			;
		}
		return;
	case 1:
		{
# line 259 "../scanProg.st"
			beginPause = 0;
			pauseStart = time(0L);
			{
# line 261 "../scanProg.st"
				Npauses = (Npauses + 1);
# line 261 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 15/*Npauses*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 262 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 262 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 262, SNLtaskName, 2);
# line 262 "../scanProg.st"
				;
# line 262 "../scanProg.st"
				printf("%s\n", "in duringScanPause, started a scan pause");
# line 262 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 262 "../scanProg.st"
			;
		}
		return;
	case 2:
		{
			/* C code definitions */
# line 266 "../scanProg.st"
			pauseSec += time(0L) - pauseStart;
# line 267 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 9/*pauseSec*/, DEFAULT, DEFAULT_TIMEOUT);
			clocks2str(pauseSec,tStr);
			{
# line 269 "../scanProg.st"
				strcpy(pauseTimeStr, tStr);
# line 269 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 6/*pauseTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 269 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 270 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 270 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 270, SNLtaskName, 2);
# line 270 "../scanProg.st"
				;
# line 270 "../scanProg.st"
				printf("%s\n", "in duringScanPause, scan pause rescinded");
# line 270 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 270 "../scanProg.st"
			;
		}
		return;
	case 3:
		{
			/* C code definitions */
# line 274 "../scanProg.st"
			now = time(0L);
# line 275 "../scanProg.st"
			clocks2str(now-pauseStart,tStr);
# line 276 "../scanProg.st"
			clocks2str(now-pauseStart+pauseSec,tStr1);
# line 277 "../scanProg.st"
			sprintf(pauseTimeStr, "current %s,  total %s", tStr, tStr1);
# line 278 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 6/*pauseTimeStr*/, DEFAULT, DEFAULT_TIMEOUT);
			clocks2str(now-startTime,tStr);
			{
# line 280 "../scanProg.st"
				strcpy(totalElapsedTimeStr, tStr);
# line 280 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 280 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 281 "../scanProg.st"
			if (fractionDone > 0.0)
			{
				/* C code definitions */
# line 282 "../scanProg.st"
				remainingSec = (1.0-fractionDone)/fractionDone * (double)(now-startTime-pauseSec);
# line 283 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 10/*remainingSec*/, DEFAULT, DEFAULT_TIMEOUT);
# line 284 "../scanProg.st"
				predictEnd = now + remainingSec;
				formatTimeStr(endingTimeStr,40,predictEnd,0);
# line 286 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 4/*endingTimeStr*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 288 "../scanProg.st"
			sprintf(new_msg, "   periodic check in duringScanPause, time paused; '%s', ", pauseTimeStr);
# line 289 "../scanProg.st"
			if (scanProgressDebug >= 5)
			{
# line 289 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 289, SNLtaskName, 5);
# line 289 "../scanProg.st"
				;
# line 289 "../scanProg.st"
				printf("%s\n", new_msg);
# line 289 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 289 "../scanProg.st"
			;
		}
		return;
	}
}

/****** Code for state "scanFinish" in state set "scanProgress" ******/

/* Event function for state "scanFinish" in state set "scanProgress" */
static seqBool seqg_event_scanProgress_0_scanFinish(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 295 "../scanProg.st"
	if (1)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "scanFinish" in state set "scanProgress" */
static void seqg_action_scanProgress_0_scanFinish(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
			/* C code definitions */
# line 296 "../scanProg.st"
			now = time(0L);
			{
# line 297 "../scanProg.st"
				strcpy(remainingTimeStr, "00:00:00");
# line 297 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 5/*remainingTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 297 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			clocks2str(now-startTime-pauseSec,tStr);
			{
# line 299 "../scanProg.st"
				strcpy(totalActiveTimeStr, tStr);
# line 299 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 8/*totalActiveTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 299 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			clocks2str(now-startTime,tStr);
			{
# line 301 "../scanProg.st"
				strcpy(totalElapsedTimeStr, tStr);
# line 301 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 7/*totalElapsedTimeStr*/, SYNC, DEFAULT_TIMEOUT);
# line 301 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
			formatTimeStr(endingTimeStr,40,now,1);
# line 303 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 4/*endingTimeStr*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 304 "../scanProg.st"
				running = (0);
# line 304 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 13/*running*/, SYNC, DEFAULT_TIMEOUT);
			}
			{
# line 305 "../scanProg.st"
				remainingSec = (0);
# line 305 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 10/*remainingSec*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 308 "../scanProg.st"
			seq_pvGetTmo(seqg_env, 21/*cpt1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 309 "../scanProg.st"
			if (scanDim >= 2)
			{
# line 310 "../scanProg.st"
				seq_pvGetTmo(seqg_env, 22/*cpt2*/, DEFAULT, DEFAULT_TIMEOUT);
# line 311 "../scanProg.st"
				if (scanDim >= 3)
				{
# line 312 "../scanProg.st"
					seq_pvGetTmo(seqg_env, 23/*cpt3*/, DEFAULT, DEFAULT_TIMEOUT);
# line 313 "../scanProg.st"
					if (scanDim >= 4)
					{
# line 314 "../scanProg.st"
						seq_pvGetTmo(seqg_env, 24/*cpt4*/, DEFAULT, DEFAULT_TIMEOUT);
					}
				}
			}
# line 318 "../scanProg.st"
			cpt = calc_cpt();
# line 319 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 12/*cpt*/, DEFAULT, DEFAULT_TIMEOUT);
			fractionDone = (double)cpt/(double)npts;
# line 321 "../scanProg.st"
			if (fractionDone > 1.0)
# line 321 "../scanProg.st"
				fractionDone = 1.0;
# line 322 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 1/*fractionDone*/, DEFAULT, DEFAULT_TIMEOUT);
			{
# line 323 "../scanProg.st"
				percentDone = (100.0 * fractionDone);
# line 323 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 2/*percentDone*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 324 "../scanProg.st"
			if (scanProgressDebug >= 2)
			{
# line 324 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 324, SNLtaskName, 2);
# line 324 "../scanProg.st"
				;
# line 324 "../scanProg.st"
				printf("%s\n", "no scan is busy in duringScan, back to idle");
# line 324 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 324 "../scanProg.st"
			;
		}
		return;
	}
}

/****** Code for state "initPause" in state set "scanPauseUpdate" ******/

/* Event function for state "initPause" in state set "scanPauseUpdate" */
static seqBool seqg_event_scanPauseUpdate_1_initPause(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "initPause" in state set "scanPauseUpdate" */
static void seqg_action_scanPauseUpdate_1_initPause(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
			{
# line 338 "../scanProg.st"
				paused = (0);
# line 338 "../scanProg.st"
				seq_pvPutTmo(seqg_env, 14/*paused*/, SYNC, DEFAULT_TIMEOUT);
			}
# line 339 "../scanProg.st"
			almostPaused = 0;
# line 340 "../scanProg.st"
			epicsThreadSleep(1.0);
# line 341 "../scanProg.st"
			seq_efSet(seqg_env, pause1_mon);
# line 342 "../scanProg.st"
			if (scanProgressDebug >= 1)
			{
# line 342 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 342, SNLtaskName, 1);
# line 342 "../scanProg.st"
				;
# line 342 "../scanProg.st"
				printf("%s\n", "completed state initPause");
# line 342 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 342 "../scanProg.st"
			;
		}
		return;
	}
}

/****** Code for state "idlePause" in state set "scanPauseUpdate" ******/

/* Event function for state "idlePause" in state set "scanPauseUpdate" */
static seqBool seqg_event_scanPauseUpdate_1_idlePause(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 348 "../scanProg.st"
	if (seq_efTest(seqg_env, pause1_mon) || seq_efTest(seqg_env, pause2_mon) || seq_efTest(seqg_env, pause3_mon) || seq_efTest(seqg_env, pause4_mon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 359 "../scanProg.st"
	if (almostPaused && (seq_efTest(seqg_env, busy1_mon) || seq_efTest(seqg_env, busy2_mon) || seq_efTest(seqg_env, busy3_mon) || seq_efTest(seqg_env, busy4_mon)))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 368 "../scanProg.st"
	if (seq_delay(seqg_env, 20.))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "idlePause" in state set "scanPauseUpdate" */
static void seqg_action_scanPauseUpdate_1_idlePause(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 349 "../scanProg.st"
			sprintf(new_msg, "at top of state idlePause, monitors are : =%d,  %d,  %d,  %d", pause1_mon, pause2_mon, pause3_mon, pause4_mon);
# line 350 "../scanProg.st"
			if (scanProgressDebug >= 7)
			{
# line 350 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 350, SNLtaskName, 7);
# line 350 "../scanProg.st"
				;
# line 350 "../scanProg.st"
				printf("%s\n", new_msg);
# line 350 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 350 "../scanProg.st"
			;
# line 352 "../scanProg.st"
			seq_efClear(seqg_env, pause1_mon);
# line 353 "../scanProg.st"
			seq_efClear(seqg_env, pause2_mon);
# line 354 "../scanProg.st"
			seq_efClear(seqg_env, pause3_mon);
# line 355 "../scanProg.st"
			seq_efClear(seqg_env, pause4_mon);
		}
		return;
	case 1:
		{
# line 360 "../scanProg.st"
			sprintf(new_msg, "paused but waiting for busy, busy flags are:  busy1=%d, busy2=%d, busy3=%d, busy4=%d", busy1, busy2, busy3, busy4);
# line 361 "../scanProg.st"
			if (scanProgressDebug >= 6)
			{
# line 361 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 361, SNLtaskName, 6);
# line 361 "../scanProg.st"
				;
# line 361 "../scanProg.st"
				printf("%s\n", new_msg);
# line 361 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 361 "../scanProg.st"
			;
# line 362 "../scanProg.st"
			seq_efClear(seqg_env, busy1_mon);
# line 363 "../scanProg.st"
			seq_efClear(seqg_env, busy2_mon);
# line 364 "../scanProg.st"
			seq_efClear(seqg_env, busy3_mon);
# line 365 "../scanProg.st"
			seq_efClear(seqg_env, busy4_mon);
		}
		return;
	case 2:
		{
# line 369 "../scanProg.st"
			if (scanProgressDebug >= 7)
			{
# line 369 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 369, SNLtaskName, 7);
# line 369 "../scanProg.st"
				;
# line 369 "../scanProg.st"
				printf("%s\n", "delay(UPDATE_DELAY_LONG) in scanPauseUpdate");
# line 369 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 369 "../scanProg.st"
			;
		}
		return;
	}
}

/****** Code for state "checkAndSetPause" in state set "scanPauseUpdate" ******/

/* Event function for state "checkAndSetPause" in state set "scanPauseUpdate" */
static seqBool seqg_event_scanPauseUpdate_1_checkAndSetPause(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 375 "../scanProg.st"
	if (1)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "checkAndSetPause" in state set "scanPauseUpdate" */
static void seqg_action_scanPauseUpdate_1_checkAndSetPause(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 376 "../scanProg.st"
			sprintf(new_msg, "paused flags are pause1=%d, pause2=%d, pause3=%d, pause4=%d", pause1, pause2, pause3, pause4);
# line 377 "../scanProg.st"
			if (scanProgressDebug >= 8)
			{
# line 377 "../scanProg.st"
				printf("<%s,%d,%s,%d> ", "../scanProg.st", 377, SNLtaskName, 8);
# line 377 "../scanProg.st"
				;
# line 377 "../scanProg.st"
				printf("%s\n", new_msg);
# line 377 "../scanProg.st"
				epicsThreadSleep(0.01);
			}
# line 377 "../scanProg.st"
			;
# line 378 "../scanProg.st"
			aPause = pause1;
# line 379 "../scanProg.st"
			if (scanDim > 1)
			{
# line 380 "../scanProg.st"
				aPause = aPause || pause2;
# line 381 "../scanProg.st"
				if (scanDim > 2)
				{
# line 382 "../scanProg.st"
					aPause = aPause || pause3;
# line 383 "../scanProg.st"
					if (scanDim > 3)
					{
# line 384 "../scanProg.st"
						aPause = aPause || pause4;
					}
				}
			}
# line 388 "../scanProg.st"
			stopped = allStopped();
# line 389 "../scanProg.st"
			almostPaused = aPause && !stopped;
# line 390 "../scanProg.st"
			paused = aPause && stopped;
# line 391 "../scanProg.st"
			seq_pvPutTmo(seqg_env, 14/*paused*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{P}debug", (size_t)&scanProgressDebug, "scanProgressDebug", P_SHORT, 1, 10, 1, 1, 0, 0},
	{"{P}fractionDone", (size_t)&fractionDone, "fractionDone", P_DOUBLE, 1, 11, 0, 0, 0, 0},
	{"{P}percentDone", (size_t)&percentDone, "percentDone", P_DOUBLE, 1, 12, 0, 0, 0, 0},
	{"{P}startingTimeStr", (size_t)&startingTimeStr, "startingTimeStr", P_STRING, 1, 13, 0, 0, 0, 0},
	{"{P}endingTimeStr", (size_t)&endingTimeStr, "endingTimeStr", P_STRING, 1, 14, 0, 0, 0, 0},
	{"{P}remainingTimeStr", (size_t)&remainingTimeStr, "remainingTimeStr", P_STRING, 1, 15, 0, 0, 0, 0},
	{"{P}pauseTimeStr", (size_t)&pauseTimeStr, "pauseTimeStr", P_STRING, 1, 16, 0, 0, 0, 0},
	{"{P}totalElapsedTimeStr", (size_t)&totalElapsedTimeStr, "totalElapsedTimeStr", P_STRING, 1, 17, 0, 0, 0, 0},
	{"{P}totalActiveTimeStr", (size_t)&totalActiveTimeStr, "totalActiveTimeStr", P_STRING, 1, 18, 0, 0, 0, 0},
	{"{P}pauseSec", (size_t)&pauseSec, "pauseSec", P_INT, 1, 19, 0, 0, 0, 0},
	{"{P}remainingSec", (size_t)&remainingSec, "remainingSec", P_INT, 1, 20, 0, 0, 0, 0},
	{"{P}Ntotal", (size_t)&npts, "npts", P_INT, 1, 21, 0, 0, 0, 0},
	{"{P}Nfinished", (size_t)&cpt, "cpt", P_INT, 1, 22, 0, 0, 0, 0},
	{"{P}running", (size_t)&running, "running", P_SHORT, 1, 23, 0, 0, 0, 0},
	{"{P}paused", (size_t)&paused, "paused", P_SHORT, 1, 24, 0, 0, 0, 0},
	{"{P}Npauses", (size_t)&Npauses, "Npauses", P_INT, 1, 25, 0, 0, 0, 0},
	{"{P}version", (size_t)&version, "version", P_DOUBLE, 1, 26, 0, 0, 0, 0},
	{"{S}scan1.NPTS", (size_t)&npts1, "npts1", P_INT, 1, 27, 0, 0, 0, 0},
	{"{S}scan2.NPTS", (size_t)&npts2, "npts2", P_INT, 1, 28, 0, 0, 0, 0},
	{"{S}scan3.NPTS", (size_t)&npts3, "npts3", P_INT, 1, 29, 0, 0, 0, 0},
	{"{S}scan4.NPTS", (size_t)&npts4, "npts4", P_INT, 1, 30, 0, 0, 0, 0},
	{"{S}scan1.CPT", (size_t)&cpt1, "cpt1", P_INT, 1, 31, 0, 0, 0, 0},
	{"{S}scan2.CPT", (size_t)&cpt2, "cpt2", P_INT, 1, 32, 0, 0, 0, 0},
	{"{S}scan3.CPT", (size_t)&cpt3, "cpt3", P_INT, 1, 33, 0, 0, 0, 0},
	{"{S}scan4.CPT", (size_t)&cpt4, "cpt4", P_INT, 1, 34, 0, 0, 0, 0},
	{"{S}scan1.PAUS", (size_t)&pause1, "pause1", P_SHORT, 1, 35, 2, 1, 0, 0},
	{"{S}scan2.PAUS", (size_t)&pause2, "pause2", P_SHORT, 1, 36, 3, 1, 0, 0},
	{"{S}scan3.PAUS", (size_t)&pause3, "pause3", P_SHORT, 1, 37, 4, 1, 0, 0},
	{"{S}scan4.PAUS", (size_t)&pause4, "pause4", P_SHORT, 1, 38, 5, 1, 0, 0},
	{"{S}scan1.BUSY", (size_t)&busy1, "busy1", P_SHORT, 1, 39, 6, 1, 0, 0},
	{"{S}scan2.BUSY", (size_t)&busy2, "busy2", P_SHORT, 1, 40, 7, 1, 0, 0},
	{"{S}scan3.BUSY", (size_t)&busy3, "busy3", P_SHORT, 1, 41, 8, 1, 0, 0},
	{"{S}scan4.BUSY", (size_t)&busy4, "busy4", P_SHORT, 1, 42, 9, 1, 0, 0},
};

/* Event masks for state set "scanProgress" */
static const seqMask seqg_mask_scanProgress_0_init[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_scanProgress_0_idle[] = {
	0x00000002,
	0x00000780,
};
static const seqMask seqg_mask_scanProgress_0_duringScan[] = {
	0x01000000,
	0x00000780,
};
static const seqMask seqg_mask_scanProgress_0_duringScanPause[] = {
	0x01000000,
	0x00000780,
};
static const seqMask seqg_mask_scanProgress_0_scanFinish[] = {
	0x00000000,
	0x00000000,
};

/* State table for state set "scanProgress" */
static seqState seqg_states_scanProgress[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_scanProgress_0_init,
	/* event function */    seqg_event_scanProgress_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanProgress_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "idle",
	/* action function */   seqg_action_scanProgress_0_idle,
	/* event function */    seqg_event_scanProgress_0_idle,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanProgress_0_idle,
	/* state options */     (0)
	},
	{
	/* state name */        "duringScan",
	/* action function */   seqg_action_scanProgress_0_duringScan,
	/* event function */    seqg_event_scanProgress_0_duringScan,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanProgress_0_duringScan,
	/* state options */     (0)
	},
	{
	/* state name */        "duringScanPause",
	/* action function */   seqg_action_scanProgress_0_duringScanPause,
	/* event function */    seqg_event_scanProgress_0_duringScanPause,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanProgress_0_duringScanPause,
	/* state options */     (0)
	},
	{
	/* state name */        "scanFinish",
	/* action function */   seqg_action_scanProgress_0_scanFinish,
	/* event function */    seqg_event_scanProgress_0_scanFinish,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanProgress_0_scanFinish,
	/* state options */     (0)
	},
};

/* Event masks for state set "scanPauseUpdate" */
static const seqMask seqg_mask_scanPauseUpdate_1_initPause[] = {
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_scanPauseUpdate_1_idlePause[] = {
	0x000003fc,
	0x00000000,
};
static const seqMask seqg_mask_scanPauseUpdate_1_checkAndSetPause[] = {
	0x00000000,
	0x00000000,
};

/* State table for state set "scanPauseUpdate" */
static seqState seqg_states_scanPauseUpdate[] = {
	{
	/* state name */        "initPause",
	/* action function */   seqg_action_scanPauseUpdate_1_initPause,
	/* event function */    seqg_event_scanPauseUpdate_1_initPause,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanPauseUpdate_1_initPause,
	/* state options */     (0)
	},
	{
	/* state name */        "idlePause",
	/* action function */   seqg_action_scanPauseUpdate_1_idlePause,
	/* event function */    seqg_event_scanPauseUpdate_1_idlePause,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanPauseUpdate_1_idlePause,
	/* state options */     (0)
	},
	{
	/* state name */        "checkAndSetPause",
	/* action function */   seqg_action_scanPauseUpdate_1_checkAndSetPause,
	/* event function */    seqg_event_scanPauseUpdate_1_checkAndSetPause,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_scanPauseUpdate_1_checkAndSetPause,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "scanProgress",
	/* states */            seqg_states_scanProgress,
	/* number of states */  5
	},

	{
	/* state set name */    "scanPauseUpdate",
	/* states */            seqg_states_scanPauseUpdate,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram scanProgress = {
	/* magic number */      2002008,
	/* program name */      "scanProgress",
	/* channels */          seqg_chans,
	/* num. channels */     33,
	/* state sets */        seqg_statesets,
	/* num. state sets */   2,
	/* user var size */     0,
	/* param */             "S=34ide:, P=34ide:scanProgress:",
	/* num. event flags */  9,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};
# line 398 "../scanProg.st"


static long calc_cpt(void)
{
 long lcpt;
 long nBelow;

 lcpt = cpt1;
 if (scanDim<2) return lcpt;

 nBelow = npts1;
 lcpt += cpt2 * nBelow;
 if (scanDim<3) return lcpt;

 nBelow *= npts2;
 lcpt += cpt3 * nBelow;
 if (scanDim<4) return lcpt;

 nBelow *= npts3;
 lcpt += cpt4*nBelow;
 return lcpt;
}




static void clocks2str(long isec, char *str)
{
 int hh,mm,ss;
 int sign=1;
 if (isec>32000000) {
  strcpy(str,"infinite");
  return;
 }
 else if (isec<-32000000) {
  strcpy(str,"-infinite");
  return;
 }
 else if (isec<0) {
  isec *= -1;
  sign = -1;
 }
 ss = isec % 60;
 isec /= 60;
 mm = isec % 60;
 hh = sign * isec / 60;
 sprintf(str,"%02d:%02d:%02d",hh,mm,ss);
 return;
}



static void formatTimeStr(
char *tStr,
int tStrLen,
long final,
int full)
{
 long now;
 struct tm *tm1;
 int isToday=0;
 int isTomorrow=0;
 int isYesterday=0;
 int hh,mm,ss;

 if (!full) {
  tm1 = localtime(&final);
  hh = tm1->tm_hour;
  mm = tm1->tm_min;
  ss = tm1->tm_sec;

  now = time(0L);
  tm1 = localtime(&now);
  tm1->tm_hour = hh;
  tm1->tm_min = mm;
  tm1->tm_sec = ss;
  isToday = (final==mktime(tm1));
  if (!isToday) {
   tm1->tm_mday++;
   isTomorrow = (final==mktime(tm1));
  }
  if (!isToday && !isTomorrow) {
   tm1->tm_mday -= 2;
   isYesterday = (final==mktime(tm1));
  }
 }

 tm1 = localtime(&final);
 if (isToday) strftime(tStr,tStrLen, "%T Today (%A)",tm1);
 else if (isTomorrow) strftime(tStr,tStrLen, "%T Tomorrow (%A)",tm1);
 else if (isYesterday) strftime(tStr,tStrLen, "%T Yesterday (%A)",tm1);
 else strftime(tStr,tStrLen, "%T  (%a) %b %e, %Y",tm1);
 return;
}


static int allStopped(void)
{
 int stopCount;

 stopCount = (pause1 || !busy1) ? 1 : 0;
 stopCount += (scanDim<2) || (pause2 || !busy2) ? 2 : 0;
 stopCount += (scanDim<3) || (pause3 || !busy3) ? 4 : 0;
 stopCount += (scanDim<4) || (pause4 || !busy4) ? 8 : 0;
 return (stopCount==15);
}



/* Register sequencer commands and program */
#include "epicsExport.h"
static void scanProgressRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&scanProgress);
}
epicsExportRegistrar(scanProgressRegistrar);
