/* C code for program parameterTest, generated by snc from ../parameter.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"

/* Variable declarations */


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "one" in state set "one" ******/

/* Event function for state "one" in state set "one" */
static seqBool seqg_event_one_0_one(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		seq_exit(seqg_env);
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "one" in state set "one" */
static void seqg_action_one_0_one(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 9 "../parameter.st"
			printf("var=%s\n", seq_macValueGet(seqg_env, "var"));
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* No channel definitions */
#define seqg_chans 0

/* Event masks for state set "one" */
static const seqMask seqg_mask_one_0_one[] = {
	0x00000000,
};

/* State table for state set "one" */
static seqState seqg_states_one[] = {
	{
	/* state name */        "one",
	/* action function */   seqg_action_one_0_one,
	/* event function */    seqg_event_one_0_one,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_one_0_one,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "one",
	/* states */            seqg_states_one,
	/* number of states */  1
	},
};

/* Program table (global) */
seqProgram parameterTest = {
	/* magic number */      2002008,
	/* program name */      "parameterTest",
	/* channels */          seqg_chans,
	/* num. channels */     0,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     0,
	/* param */             "var=default",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

#define PROG_NAME parameterTest
#include "seqMain.c"

/* Register sequencer commands and program */
#include "epicsExport.h"
static void parameterTestRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&parameterTest);
}
epicsExportRegistrar(parameterTestRegistrar);
