/* C code for program editSseq, generated by snc from ../editSseq.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 39 "../editSseq.st"
static int lineNum(char c);
# line 40 "../editSseq.st"
static char fieldChar(int n);
# line 41 "../editSseq.st"
static char fieldCharCheck(char c);
# line 42 "../editSseq.st"
static int reconcilePVs(SS_ID ssId, struct UserVar *pVar,
# line 43 "../editSseq.st"
char *pattern, string *PV, int *PVIndex, char c_dest);
# line 62 "../editSseq.st"
static const EF_ID recordNameMon = 1;
# line 75 "../editSseq.st"
static const EF_ID commandMon = 2;
# line 104 "../editSseq.st"
#include <string.h>
# line 105 "../editSseq.st"
#include <math.h>
# line 106 "../editSseq.st"
#include <stdlib.h>
# line 107 "../editSseq.st"
#include <ctype.h>

/* Variable declarations */
struct seqg_vars {
# line 45 "../editSseq.st"
	short Debug;
# line 49 "../editSseq.st"
	string message;
# line 52 "../editSseq.st"
	short opAlert;
# line 55 "../editSseq.st"
	short opAck;
# line 59 "../editSseq.st"
	string recordName;
# line 67 "../editSseq.st"
	int recType;
# line 69 "../editSseq.st"
	string recordType;
# line 72 "../editSseq.st"
	string command;
# line 80 "../editSseq.st"
	string DOL[11];
# line 82 "../editSseq.st"
	double DLY[11];
# line 84 "../editSseq.st"
	string STR[11];
# line 86 "../editSseq.st"
	double DO[11];
# line 88 "../editSseq.st"
	string LNK[11];
# line 90 "../editSseq.st"
	string WAIT[11];
# line 93 "../editSseq.st"
	int DOLIndex[10];
# line 94 "../editSseq.st"
	int STRIndex[10];
# line 95 "../editSseq.st"
	int LNKIndex[10];
# line 96 "../editSseq.st"
	int WAITIndex[10];
# line 98 "../editSseq.st"
	int i;
# line 98 "../editSseq.st"
	int j;
# line 98 "../editSseq.st"
	int src;
# line 98 "../editSseq.st"
	int dest;
# line 98 "../editSseq.st"
	int inc;
# line 98 "../editSseq.st"
	int n;
# line 98 "../editSseq.st"
	int permit;
# line 99 "../editSseq.st"
	string fieldName;
# line 99 "../editSseq.st"
	string pattern;
# line 100 "../editSseq.st"
	int rewroteRecordName;
# line 101 "../editSseq.st"
	char *s;
# line 101 "../editSseq.st"
	char c;
# line 101 "../editSseq.st"
	char c_src;
# line 101 "../editSseq.st"
	char c_dest;
# line 102 "../editSseq.st"
	int ic;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "editSseq" ******/

/* Entry function for state "init" in state set "editSseq" */
static void seqg_entry_editSseq_0_init(SS_ID seqg_env)
{
# line 117 "../editSseq.st"
	if (seqg_var->Debug)
# line 117 "../editSseq.st"
		printf("editSseq:init: entry\n");
}

/* Event function for state "init" in state set "editSseq" */
static seqBool seqg_event_editSseq_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "editSseq" */
static void seqg_action_editSseq_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 120 "../editSseq.st"
			seqg_var->rewroteRecordName = 0;
# line 121 "../editSseq.st"
			strcpy(seqg_var->recordType, "");
# line 122 "../editSseq.st"
			seqg_var->recType = 0;
# line 123 "../editSseq.st"
			strcpy(seqg_var->message, "");
# line 124 "../editSseq.st"
			seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 125 "../editSseq.st"
			seqg_var->opAlert = 0;
# line 126 "../editSseq.st"
			seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 127 "../editSseq.st"
			seq_efClear(seqg_env, commandMon);
		}
		return;
	}
}

/****** Code for state "waitForCmnd" in state set "editSseq" ******/

/* Entry function for state "waitForCmnd" in state set "editSseq" */
static void seqg_entry_editSseq_0_waitForCmnd(SS_ID seqg_env)
{
# line 133 "../editSseq.st"
	if (seqg_var->Debug > 10)
# line 133 "../editSseq.st"
		printf("editSseq:waitForCmnd: entry\n");
# line 134 "../editSseq.st"
	if (seqg_var->rewroteRecordName)
	{
# line 135 "../editSseq.st"
		seq_efClear(seqg_env, recordNameMon);
# line 136 "../editSseq.st"
		seqg_var->rewroteRecordName = 0;
	}
}

/* Event function for state "waitForCmnd" in state set "editSseq" */
static seqBool seqg_event_editSseq_0_waitForCmnd(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 139 "../editSseq.st"
	if (seq_efTestAndClear(seqg_env, commandMon))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 141 "../editSseq.st"
	if (seq_efTestAndClear(seqg_env, recordNameMon))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 143 "../editSseq.st"
	if (seqg_var->opAck)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "waitForCmnd" in state set "editSseq" */
static void seqg_action_editSseq_0_waitForCmnd(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	case 2:
		{
# line 144 "../editSseq.st"
			strcpy(seqg_var->message, "");
# line 145 "../editSseq.st"
			seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 146 "../editSseq.st"
			seqg_var->opAlert = 0;
# line 147 "../editSseq.st"
			seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
# line 148 "../editSseq.st"
			seqg_var->opAck = 0;
# line 149 "../editSseq.st"
			seq_pvPutTmo(seqg_env, 3/*opAck*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "newRecordName" in state set "editSseq" ******/

/* Entry function for state "newRecordName" in state set "editSseq" */
static void seqg_entry_editSseq_0_newRecordName(SS_ID seqg_env)
{
# line 155 "../editSseq.st"
	if (seqg_var->Debug)
# line 155 "../editSseq.st"
		printf("editSseq:newRecordName: entry\n");
# line 156 "../editSseq.st"
	if (seqg_var->Debug)
# line 156 "../editSseq.st"
		printf("editSseq:newRecordName: recordName='%s'\n", seqg_var->recordName);
# line 158 "../editSseq.st"
	if (*seqg_var->recordName)
	{
# line 159 "../editSseq.st"
		seqg_var->s = strchr(seqg_var->recordName, '.');
# line 160 "../editSseq.st"
		if (seqg_var->s)
		{
# line 161 "../editSseq.st"
			*seqg_var->s = '\0';
# line 162 "../editSseq.st"
			seq_pvPutTmo(seqg_env, 4/*recordName*/, DEFAULT, DEFAULT_TIMEOUT);
# line 163 "../editSseq.st"
			seqg_var->rewroteRecordName = 1;
		}
	}
# line 166 "../editSseq.st"
	if (seqg_var->Debug)
# line 166 "../editSseq.st"
		printf("editSseq:newRecordName: recordName='%s'\n", seqg_var->recordName);
# line 167 "../editSseq.st"
	strcpy(seqg_var->recordType, "");
# line 168 "../editSseq.st"
	seqg_var->recType = 0;
}

/* Event function for state "newRecordName" in state set "editSseq" */
static seqBool seqg_event_editSseq_0_newRecordName(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "newRecordName" in state set "editSseq" */
static void seqg_action_editSseq_0_newRecordName(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 171 "../editSseq.st"
			sprintf(seqg_var->fieldName, "%s.RTYP", seqg_var->recordName);
# line 172 "../editSseq.st"
			seq_pvAssign(seqg_env, 5/*recordType*/, seqg_var->fieldName);
# line 173 "../editSseq.st"
			seq_pvGetTmo(seqg_env, 5/*recordType*/, DEFAULT, DEFAULT_TIMEOUT);
# line 174 "../editSseq.st"
			if (strcmp(seqg_var->recordType, "sseq") == 0)
			{
# line 175 "../editSseq.st"
				seqg_var->recType = 1;
			}
			else
# line 176 "../editSseq.st"
				if (strcmp(seqg_var->recordType, "seq") == 0)
				{
# line 177 "../editSseq.st"
					seqg_var->recType = 2;
				}
				else
				{
# line 179 "../editSseq.st"
					seqg_var->recType = 0;
				}
# line 181 "../editSseq.st"
			for (seqg_var->i = 0; seqg_var->i < 10; seqg_var->i++)
			{
# line 182 "../editSseq.st"
				sprintf(seqg_var->fieldName, "%s.DOL%c", seqg_var->recordName, fieldChar(seqg_var->i));
# line 183 "../editSseq.st"
				seq_pvAssign(seqg_env, 7/*DOL*/ + (CH_ID)(seqg_var->i), seqg_var->fieldName);
# line 184 "../editSseq.st"
				seqg_var->DOLIndex[seqg_var->i] = seq_pvIndex(seqg_env, 7/*DOL*/ + (CH_ID)(seqg_var->i));
# line 186 "../editSseq.st"
				sprintf(seqg_var->fieldName, "%s.DLY%c", seqg_var->recordName, fieldChar(seqg_var->i));
# line 187 "../editSseq.st"
				seq_pvAssign(seqg_env, 18/*DLY*/ + (CH_ID)(seqg_var->i), seqg_var->fieldName);
# line 189 "../editSseq.st"
				sprintf(seqg_var->fieldName, "%s.DO%c", seqg_var->recordName, fieldChar(seqg_var->i));
# line 190 "../editSseq.st"
				seq_pvAssign(seqg_env, 40/*DO*/ + (CH_ID)(seqg_var->i), seqg_var->fieldName);
# line 192 "../editSseq.st"
				sprintf(seqg_var->fieldName, "%s.LNK%c", seqg_var->recordName, fieldChar(seqg_var->i));
# line 193 "../editSseq.st"
				seq_pvAssign(seqg_env, 51/*LNK*/ + (CH_ID)(seqg_var->i), seqg_var->fieldName);
# line 194 "../editSseq.st"
				seqg_var->LNKIndex[seqg_var->i] = seq_pvIndex(seqg_env, 51/*LNK*/ + (CH_ID)(seqg_var->i));
# line 196 "../editSseq.st"
				if (seqg_var->recType == 1)
				{
# line 197 "../editSseq.st"
					sprintf(seqg_var->fieldName, "%s.STR%c", seqg_var->recordName, fieldChar(seqg_var->i));
# line 198 "../editSseq.st"
					seq_pvAssign(seqg_env, 29/*STR*/ + (CH_ID)(seqg_var->i), seqg_var->fieldName);
# line 199 "../editSseq.st"
					seqg_var->STRIndex[seqg_var->i] = seq_pvIndex(seqg_env, 29/*STR*/ + (CH_ID)(seqg_var->i));
# line 201 "../editSseq.st"
					sprintf(seqg_var->fieldName, "%s.WAIT%c", seqg_var->recordName, fieldChar(seqg_var->i));
# line 202 "../editSseq.st"
					seq_pvAssign(seqg_env, 62/*WAIT*/ + (CH_ID)(seqg_var->i), seqg_var->fieldName);
# line 203 "../editSseq.st"
					seqg_var->WAITIndex[seqg_var->i] = seq_pvIndex(seqg_env, 62/*WAIT*/ + (CH_ID)(seqg_var->i));
				}
			}
		}
		return;
	}
}

/****** Code for state "newCommand" in state set "editSseq" ******/

/* Entry function for state "newCommand" in state set "editSseq" */
static void seqg_entry_editSseq_0_newCommand(SS_ID seqg_env)
{
# line 212 "../editSseq.st"
	if (seqg_var->Debug)
	{
# line 213 "../editSseq.st"
		printf("editSseq:newCommand: entry\n");
# line 214 "../editSseq.st"
		printf("editSseq:newCommand: command: '%s'\n", seqg_var->command);
# line 215 "../editSseq.st"
		printf("editSseq:newCommand: recordType=%s\n", seqg_var->recordType);
# line 216 "../editSseq.st"
		printf("editSseq:newCommand: recType=%d\n", seqg_var->recType);
	}
# line 218 "../editSseq.st"
	for (seqg_var->i = 0; seqg_var->i < 10; seqg_var->i++)
	{
# line 219 "../editSseq.st"
		if (seqg_var->recType == 2 || seqg_var->recType == 1)
		{
# line 220 "../editSseq.st"
			seq_pvGetTmo(seqg_env, 7/*DOL*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 221 "../editSseq.st"
			seq_pvGetTmo(seqg_env, 18/*DLY*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 222 "../editSseq.st"
			seq_pvGetTmo(seqg_env, 40/*DO*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 223 "../editSseq.st"
			seq_pvGetTmo(seqg_env, 51/*LNK*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 224 "../editSseq.st"
			if (seqg_var->recType == 1)
			{
# line 225 "../editSseq.st"
				seq_pvGetTmo(seqg_env, 29/*STR*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
# line 226 "../editSseq.st"
				seq_pvGetTmo(seqg_env, 62/*WAIT*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
			}
		}
	}
# line 230 "../editSseq.st"
	strcpy(seqg_var->message, "");
# line 231 "../editSseq.st"
	seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 232 "../editSseq.st"
	seqg_var->opAlert = 0;
# line 233 "../editSseq.st"
	seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
}

/* Event function for state "newCommand" in state set "editSseq" */
static seqBool seqg_event_editSseq_0_newCommand(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 236 "../editSseq.st"
	if (strcmp(seqg_var->command, "") == 0)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 239 "../editSseq.st"
	if (seqg_var->recType == 0)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 247 "../editSseq.st"
	if ((seqg_var->command[1] == '+') || (seqg_var->command[1] == '-'))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 2;
		return TRUE;
	}
# line 361 "../editSseq.st"
	if (strchr(seqg_var->command, '/') != 0)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 3;
		return TRUE;
	}
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 4;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "newCommand" in state set "editSseq" */
static void seqg_action_editSseq_0_newCommand(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
# line 240 "../editSseq.st"
			sprintf(seqg_var->message, "unsupported recordType '%s'", seqg_var->recordType);
# line 241 "../editSseq.st"
			seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 242 "../editSseq.st"
			seqg_var->opAlert = 1;
# line 243 "../editSseq.st"
			seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 2:
		{
# line 248 "../editSseq.st"
			if (seqg_var->Debug)
# line 248 "../editSseq.st"
				printf("command '+/-'\n");
# line 249 "../editSseq.st"
			seqg_var->c_src = fieldCharCheck(seqg_var->command[0]);
# line 250 "../editSseq.st"
			seqg_var->src = lineNum(seqg_var->c_src);
# line 251 "../editSseq.st"
			if (seqg_var->command[1] == '+')
			{
# line 252 "../editSseq.st"
				seqg_var->dest = seqg_var->src + 1;
			}
			else
			{
# line 254 "../editSseq.st"
				seqg_var->dest = seqg_var->src - 1;
			}
# line 256 "../editSseq.st"
			seqg_var->c_dest = fieldChar(seqg_var->dest);
# line 257 "../editSseq.st"
			if (seqg_var->Debug)
# line 257 "../editSseq.st"
				printf("src='%c'(%d), dest='%c'(%d)\n", seqg_var->c_src, seqg_var->src, seqg_var->c_dest, seqg_var->dest);
# line 259 "../editSseq.st"
			seqg_var->permit = 1;
# line 262 "../editSseq.st"
			sprintf(seqg_var->pattern, "%s.DO%c", seqg_var->recordName, seqg_var->c_dest);
# line 263 "../editSseq.st"
			for (seqg_var->i = 0; seqg_var->i < 10; seqg_var->i++)
			{
# line 264 "../editSseq.st"
				if (strstr(seqg_var->DOL[seqg_var->i], seqg_var->pattern) != 0)
				{
# line 265 "../editSseq.st"
					seqg_var->permit = 0;
# line 266 "../editSseq.st"
					sprintf(seqg_var->message, ("DOL%c would be orphaned"), (fieldChar(seqg_var->i)));
# line 266 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 266 "../editSseq.st"
					seqg_var->opAlert = 1;
# line 266 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 270 "../editSseq.st"
			sprintf(seqg_var->pattern, "%s.DO%c", seqg_var->recordName, seqg_var->c_dest);
# line 271 "../editSseq.st"
			for (seqg_var->i = 0; seqg_var->i < 10; seqg_var->i++)
			{
# line 272 "../editSseq.st"
				if (strstr(seqg_var->LNK[seqg_var->i], seqg_var->pattern) != 0)
				{
# line 273 "../editSseq.st"
					seqg_var->permit = 0;
# line 274 "../editSseq.st"
					sprintf(seqg_var->message, ("LNK%c would be orphaned"), (fieldChar(seqg_var->i)));
# line 274 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 274 "../editSseq.st"
					seqg_var->opAlert = 1;
# line 274 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
				}
			}
# line 277 "../editSseq.st"
			if (seqg_var->recType == 1)
			{
# line 279 "../editSseq.st"
				sprintf(seqg_var->pattern, "After%c", seqg_var->c_dest);
# line 280 "../editSseq.st"
				for (seqg_var->i = 0; seqg_var->i < 10; seqg_var->i++)
				{
# line 281 "../editSseq.st"
					if (strstr(seqg_var->WAIT[seqg_var->i], seqg_var->pattern) != 0)
					{
# line 282 "../editSseq.st"
						seqg_var->permit = 0;
# line 283 "../editSseq.st"
						sprintf(seqg_var->message, ("WAIT%c would be orphaned"), (fieldChar(seqg_var->i)));
# line 283 "../editSseq.st"
						seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 283 "../editSseq.st"
						seqg_var->opAlert = 1;
# line 283 "../editSseq.st"
						seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
					}
				}
# line 288 "../editSseq.st"
				sprintf(seqg_var->pattern, "%s.STR%c", seqg_var->recordName, seqg_var->c_dest);
# line 289 "../editSseq.st"
				for (seqg_var->i = 0; seqg_var->i < 10; seqg_var->i++)
				{
# line 290 "../editSseq.st"
					if (strstr(seqg_var->DOL[seqg_var->i], seqg_var->pattern) != 0)
					{
# line 291 "../editSseq.st"
						seqg_var->permit = 0;
# line 292 "../editSseq.st"
						sprintf(seqg_var->message, ("DOL%c would be orphaned"), (fieldChar(seqg_var->i)));
# line 292 "../editSseq.st"
						seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 292 "../editSseq.st"
						seqg_var->opAlert = 1;
# line 292 "../editSseq.st"
						seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
					}
				}
# line 296 "../editSseq.st"
				sprintf(seqg_var->pattern, "%s.STR%c", seqg_var->recordName, seqg_var->c_dest);
# line 297 "../editSseq.st"
				for (seqg_var->i = 0; seqg_var->i < 10; seqg_var->i++)
				{
# line 298 "../editSseq.st"
					if (strstr(seqg_var->LNK[seqg_var->i], seqg_var->pattern) != 0)
					{
# line 299 "../editSseq.st"
						seqg_var->permit = 0;
# line 300 "../editSseq.st"
						sprintf(seqg_var->message, ("LNK%c would be orphaned"), (fieldChar(seqg_var->i)));
# line 300 "../editSseq.st"
						seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 300 "../editSseq.st"
						seqg_var->opAlert = 1;
# line 300 "../editSseq.st"
						seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
					}
				}
			}
# line 305 "../editSseq.st"
			if (seqg_var->permit && seqg_var->src >= 0 && seqg_var->src <= 9 && seqg_var->dest >= 0 && seqg_var->dest <= 9)
			{
# line 306 "../editSseq.st"
				strcpy(seqg_var->DOL[seqg_var->dest], seqg_var->DOL[seqg_var->src]);
# line 307 "../editSseq.st"
				strcpy(seqg_var->DOL[seqg_var->src], "");
# line 308 "../editSseq.st"
				seqg_var->DLY[seqg_var->dest] = seqg_var->DLY[seqg_var->src];
# line 309 "../editSseq.st"
				seqg_var->DLY[seqg_var->src] = 0;
# line 310 "../editSseq.st"
				seqg_var->DO[seqg_var->dest] = seqg_var->DO[seqg_var->src];
# line 311 "../editSseq.st"
				seqg_var->DO[seqg_var->src] = 0;
# line 312 "../editSseq.st"
				strcpy(seqg_var->LNK[seqg_var->dest], seqg_var->LNK[seqg_var->src]);
# line 313 "../editSseq.st"
				strcpy(seqg_var->LNK[seqg_var->src], "");
# line 316 "../editSseq.st"
				sprintf(seqg_var->pattern, "%s.DO%c", seqg_var->recordName, seqg_var->c_src);
				reconcilePVs(ssId, pVar, pVar->pattern, pVar->LNK, pVar->LNKIndex, pVar->c_dest);
# line 320 "../editSseq.st"
				sprintf(seqg_var->pattern, "%s.DO%c", seqg_var->recordName, seqg_var->c_src);
				reconcilePVs(ssId, pVar, pVar->pattern, pVar->DOL, pVar->DOLIndex, pVar->c_dest);
# line 323 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 7/*DOL*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 324 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 7/*DOL*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
# line 325 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 18/*DLY*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 326 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 18/*DLY*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
# line 327 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 40/*DO*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 328 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 40/*DO*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
# line 329 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 51/*LNK*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 330 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 51/*LNK*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
# line 332 "../editSseq.st"
				if (seqg_var->recType == 1)
				{
# line 333 "../editSseq.st"
					strcpy(seqg_var->STR[seqg_var->dest], seqg_var->STR[seqg_var->src]);
# line 334 "../editSseq.st"
					strcpy(seqg_var->STR[seqg_var->src], "");
# line 335 "../editSseq.st"
					strcpy(seqg_var->WAIT[seqg_var->dest], seqg_var->WAIT[seqg_var->src]);
# line 336 "../editSseq.st"
					strcpy(seqg_var->WAIT[seqg_var->src], "NoWait");
# line 339 "../editSseq.st"
					sprintf(seqg_var->pattern, "After%c", seqg_var->c_src);
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->WAIT, pVar->WAITIndex, pVar->c_dest);
# line 343 "../editSseq.st"
					sprintf(seqg_var->pattern, "%s.STR%c", seqg_var->recordName, seqg_var->c_src);
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->LNK, pVar->LNKIndex, pVar->c_dest);
# line 347 "../editSseq.st"
					sprintf(seqg_var->pattern, "%s.STR%c", seqg_var->recordName, seqg_var->c_src);
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->DOL, pVar->DOLIndex, pVar->c_dest);
# line 350 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 29/*STR*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 351 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 29/*STR*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
# line 352 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 62/*WAIT*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 353 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 62/*WAIT*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
				}
			}
			else
			{
# line 356 "../editSseq.st"
				if (seqg_var->permit)
# line 356 "../editSseq.st"
					sprintf(seqg_var->message, ("src (%c) out of range"), (seqg_var->command[1]));
# line 356 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 356 "../editSseq.st"
				seqg_var->opAlert = 1;
# line 356 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	case 3:
		{
# line 362 "../editSseq.st"
			if (seqg_var->Debug)
# line 362 "../editSseq.st"
				printf("command '/'\n");
# line 363 "../editSseq.st"
			seqg_var->c_src = fieldCharCheck(seqg_var->command[0]);
# line 364 "../editSseq.st"
			seqg_var->src = lineNum(seqg_var->c_src);
# line 365 "../editSseq.st"
			seqg_var->c_dest = fieldCharCheck(seqg_var->command[2]);
# line 366 "../editSseq.st"
			seqg_var->dest = lineNum(seqg_var->c_dest);
# line 367 "../editSseq.st"
			if (seqg_var->Debug)
# line 367 "../editSseq.st"
				printf("swap src='%c'(%d), dest='%c'(%d)\n", seqg_var->c_src, seqg_var->src, seqg_var->c_dest, seqg_var->dest);
# line 369 "../editSseq.st"
			if (seqg_var->src >= 0 && seqg_var->src <= 9 && seqg_var->dest >= 0 && seqg_var->dest <= 9)
			{
# line 370 "../editSseq.st"
				strcpy(seqg_var->DOL[10], seqg_var->DOL[seqg_var->dest]);
# line 371 "../editSseq.st"
				strcpy(seqg_var->DOL[seqg_var->dest], seqg_var->DOL[seqg_var->src]);
# line 372 "../editSseq.st"
				strcpy(seqg_var->DOL[seqg_var->src], seqg_var->DOL[10]);
# line 374 "../editSseq.st"
				seqg_var->DLY[10] = seqg_var->DLY[seqg_var->dest];
# line 375 "../editSseq.st"
				seqg_var->DLY[seqg_var->dest] = seqg_var->DLY[seqg_var->src];
# line 376 "../editSseq.st"
				seqg_var->DLY[seqg_var->src] = seqg_var->DLY[10];
# line 378 "../editSseq.st"
				seqg_var->DO[10] = seqg_var->DO[seqg_var->dest];
# line 379 "../editSseq.st"
				seqg_var->DO[seqg_var->dest] = seqg_var->DO[seqg_var->src];
# line 380 "../editSseq.st"
				seqg_var->DO[seqg_var->src] = seqg_var->DO[10];
# line 382 "../editSseq.st"
				strcpy(seqg_var->LNK[10], seqg_var->LNK[seqg_var->dest]);
# line 383 "../editSseq.st"
				strcpy(seqg_var->LNK[seqg_var->dest], seqg_var->LNK[seqg_var->src]);
# line 384 "../editSseq.st"
				strcpy(seqg_var->LNK[seqg_var->src], seqg_var->LNK[10]);
# line 387 "../editSseq.st"
				sprintf(seqg_var->pattern, "%s.DO%c", seqg_var->recordName, seqg_var->c_src);
				reconcilePVs(ssId, pVar, pVar->pattern, pVar->LNK, pVar->LNKIndex, '*');
# line 389 "../editSseq.st"
				sprintf(seqg_var->pattern, "%s.DO%c", seqg_var->recordName, seqg_var->c_dest);
				reconcilePVs(ssId, pVar, pVar->pattern, pVar->LNK, pVar->LNKIndex, pVar->c_src);
# line 391 "../editSseq.st"
				sprintf(seqg_var->pattern, "%s.DO%c", seqg_var->recordName, '*');
				reconcilePVs(ssId, pVar, pVar->pattern, pVar->LNK, pVar->LNKIndex, pVar->c_dest);
# line 395 "../editSseq.st"
				sprintf(seqg_var->pattern, "%s.DO%c", seqg_var->recordName, seqg_var->c_src);
				reconcilePVs(ssId, pVar, pVar->pattern, pVar->DOL, pVar->DOLIndex, '*');
# line 397 "../editSseq.st"
				sprintf(seqg_var->pattern, "%s.DO%c", seqg_var->recordName, seqg_var->c_dest);
				reconcilePVs(ssId, pVar, pVar->pattern, pVar->DOL, pVar->DOLIndex, pVar->c_src);
# line 399 "../editSseq.st"
				sprintf(seqg_var->pattern, "%s.DO%c", seqg_var->recordName, '*');
				reconcilePVs(ssId, pVar, pVar->pattern, pVar->DOL, pVar->DOLIndex, pVar->c_dest);
# line 402 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 7/*DOL*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 403 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 7/*DOL*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
# line 404 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 18/*DLY*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 405 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 18/*DLY*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
# line 406 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 40/*DO*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 407 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 40/*DO*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
# line 408 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 51/*LNK*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 409 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 51/*LNK*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
# line 411 "../editSseq.st"
				if (seqg_var->recType == 1)
				{
# line 412 "../editSseq.st"
					strcpy(seqg_var->STR[10], seqg_var->STR[seqg_var->dest]);
# line 413 "../editSseq.st"
					strcpy(seqg_var->STR[seqg_var->dest], seqg_var->STR[seqg_var->src]);
# line 414 "../editSseq.st"
					strcpy(seqg_var->STR[seqg_var->src], seqg_var->STR[10]);
# line 416 "../editSseq.st"
					strcpy(seqg_var->WAIT[10], seqg_var->WAIT[seqg_var->dest]);
# line 417 "../editSseq.st"
					strcpy(seqg_var->WAIT[seqg_var->dest], seqg_var->WAIT[seqg_var->src]);
# line 418 "../editSseq.st"
					strcpy(seqg_var->WAIT[seqg_var->src], seqg_var->WAIT[10]);
# line 421 "../editSseq.st"
					sprintf(seqg_var->pattern, "After%c", seqg_var->c_src);
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->WAIT, pVar->WAITIndex, '*');
# line 423 "../editSseq.st"
					sprintf(seqg_var->pattern, "After%c", seqg_var->c_dest);
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->WAIT, pVar->WAITIndex, pVar->c_src);
# line 425 "../editSseq.st"
					sprintf(seqg_var->pattern, "After%c", '*');
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->WAIT, pVar->WAITIndex, pVar->c_dest);
# line 429 "../editSseq.st"
					sprintf(seqg_var->pattern, "%s.STR%c", seqg_var->recordName, seqg_var->c_src);
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->LNK, pVar->LNKIndex, '*');
# line 431 "../editSseq.st"
					sprintf(seqg_var->pattern, "%s.STR%c", seqg_var->recordName, seqg_var->c_dest);
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->LNK, pVar->LNKIndex, pVar->c_src);
# line 433 "../editSseq.st"
					sprintf(seqg_var->pattern, "%s.STR%c", seqg_var->recordName, '*');
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->LNK, pVar->LNKIndex, pVar->c_dest);
# line 437 "../editSseq.st"
					sprintf(seqg_var->pattern, "%s.STR%c", seqg_var->recordName, seqg_var->c_src);
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->DOL, pVar->DOLIndex, '*');
# line 439 "../editSseq.st"
					sprintf(seqg_var->pattern, "%s.STR%c", seqg_var->recordName, seqg_var->c_dest);
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->DOL, pVar->DOLIndex, pVar->c_src);
# line 441 "../editSseq.st"
					sprintf(seqg_var->pattern, "%s.STR%c", seqg_var->recordName, '*');
					reconcilePVs(ssId, pVar, pVar->pattern, pVar->DOL, pVar->DOLIndex, pVar->c_dest);
# line 444 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 29/*STR*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 445 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 29/*STR*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
# line 446 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 62/*WAIT*/ + (CH_ID)(seqg_var->src), DEFAULT, DEFAULT_TIMEOUT);
# line 447 "../editSseq.st"
					seq_pvPutTmo(seqg_env, 62/*WAIT*/ + (CH_ID)(seqg_var->dest), DEFAULT, DEFAULT_TIMEOUT);
				}
			}
			else
			{
# line 450 "../editSseq.st"
				sprintf(seqg_var->message, "src (%c) out of range", seqg_var->command[1]);
# line 451 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 1/*message*/, DEFAULT, DEFAULT_TIMEOUT);
# line 452 "../editSseq.st"
				seqg_var->opAlert = 1;
# line 453 "../editSseq.st"
				seq_pvPutTmo(seqg_env, 2/*opAlert*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	case 4:
		{
# line 458 "../editSseq.st"
			if (seqg_var->Debug)
# line 458 "../editSseq.st"
				printf("unimplemented command '%s'\n", seqg_var->command);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"{P}{Q}Debug", offsetof(struct seqg_vars, Debug), "Debug", P_SHORT, 1, 3, 0, 1, 0, 0},
	{"{P}{Q}message", offsetof(struct seqg_vars, message), "message", P_STRING, 1, 4, 0, 0, 0, 0},
	{"{P}{Q}Alert", offsetof(struct seqg_vars, opAlert), "opAlert", P_SHORT, 1, 5, 0, 0, 0, 0},
	{"{P}{Q}OperAck", offsetof(struct seqg_vars, opAck), "opAck", P_SHORT, 1, 6, 0, 1, 0, 0},
	{"{P}{Q}recordName", offsetof(struct seqg_vars, recordName), "recordName", P_STRING, 1, 7, 1, 1, 0, 0},
	{"", offsetof(struct seqg_vars, recordType), "recordType", P_STRING, 1, 8, 0, 0, 0, 0},
	{"{P}{Q}command", offsetof(struct seqg_vars, command), "command", P_STRING, 1, 9, 2, 1, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[0]), "DOL[0]", P_STRING, 1, 10, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[1]), "DOL[1]", P_STRING, 1, 11, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[2]), "DOL[2]", P_STRING, 1, 12, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[3]), "DOL[3]", P_STRING, 1, 13, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[4]), "DOL[4]", P_STRING, 1, 14, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[5]), "DOL[5]", P_STRING, 1, 15, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[6]), "DOL[6]", P_STRING, 1, 16, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[7]), "DOL[7]", P_STRING, 1, 17, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[8]), "DOL[8]", P_STRING, 1, 18, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[9]), "DOL[9]", P_STRING, 1, 19, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DOL[10]), "DOL[10]", P_STRING, 1, 20, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[0]), "DLY[0]", P_DOUBLE, 1, 21, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[1]), "DLY[1]", P_DOUBLE, 1, 22, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[2]), "DLY[2]", P_DOUBLE, 1, 23, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[3]), "DLY[3]", P_DOUBLE, 1, 24, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[4]), "DLY[4]", P_DOUBLE, 1, 25, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[5]), "DLY[5]", P_DOUBLE, 1, 26, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[6]), "DLY[6]", P_DOUBLE, 1, 27, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[7]), "DLY[7]", P_DOUBLE, 1, 28, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[8]), "DLY[8]", P_DOUBLE, 1, 29, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[9]), "DLY[9]", P_DOUBLE, 1, 30, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DLY[10]), "DLY[10]", P_DOUBLE, 1, 31, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[0]), "STR[0]", P_STRING, 1, 32, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[1]), "STR[1]", P_STRING, 1, 33, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[2]), "STR[2]", P_STRING, 1, 34, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[3]), "STR[3]", P_STRING, 1, 35, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[4]), "STR[4]", P_STRING, 1, 36, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[5]), "STR[5]", P_STRING, 1, 37, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[6]), "STR[6]", P_STRING, 1, 38, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[7]), "STR[7]", P_STRING, 1, 39, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[8]), "STR[8]", P_STRING, 1, 40, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[9]), "STR[9]", P_STRING, 1, 41, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, STR[10]), "STR[10]", P_STRING, 1, 42, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[0]), "DO[0]", P_DOUBLE, 1, 43, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[1]), "DO[1]", P_DOUBLE, 1, 44, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[2]), "DO[2]", P_DOUBLE, 1, 45, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[3]), "DO[3]", P_DOUBLE, 1, 46, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[4]), "DO[4]", P_DOUBLE, 1, 47, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[5]), "DO[5]", P_DOUBLE, 1, 48, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[6]), "DO[6]", P_DOUBLE, 1, 49, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[7]), "DO[7]", P_DOUBLE, 1, 50, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[8]), "DO[8]", P_DOUBLE, 1, 51, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[9]), "DO[9]", P_DOUBLE, 1, 52, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, DO[10]), "DO[10]", P_DOUBLE, 1, 53, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[0]), "LNK[0]", P_STRING, 1, 54, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[1]), "LNK[1]", P_STRING, 1, 55, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[2]), "LNK[2]", P_STRING, 1, 56, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[3]), "LNK[3]", P_STRING, 1, 57, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[4]), "LNK[4]", P_STRING, 1, 58, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[5]), "LNK[5]", P_STRING, 1, 59, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[6]), "LNK[6]", P_STRING, 1, 60, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[7]), "LNK[7]", P_STRING, 1, 61, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[8]), "LNK[8]", P_STRING, 1, 62, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[9]), "LNK[9]", P_STRING, 1, 63, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, LNK[10]), "LNK[10]", P_STRING, 1, 64, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[0]), "WAIT[0]", P_STRING, 1, 65, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[1]), "WAIT[1]", P_STRING, 1, 66, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[2]), "WAIT[2]", P_STRING, 1, 67, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[3]), "WAIT[3]", P_STRING, 1, 68, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[4]), "WAIT[4]", P_STRING, 1, 69, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[5]), "WAIT[5]", P_STRING, 1, 70, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[6]), "WAIT[6]", P_STRING, 1, 71, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[7]), "WAIT[7]", P_STRING, 1, 72, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[8]), "WAIT[8]", P_STRING, 1, 73, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[9]), "WAIT[9]", P_STRING, 1, 74, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, WAIT[10]), "WAIT[10]", P_STRING, 1, 75, 0, 0, 0, 0},
};

/* Event masks for state set "editSseq" */
static const seqMask seqg_mask_editSseq_0_init[] = {
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_editSseq_0_waitForCmnd[] = {
	0x00000046,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_editSseq_0_newRecordName[] = {
	0x00000000,
	0x00000000,
	0x00000000,
};
static const seqMask seqg_mask_editSseq_0_newCommand[] = {
	0x00000200,
	0x00000000,
	0x00000000,
};

/* State table for state set "editSseq" */
static seqState seqg_states_editSseq[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_editSseq_0_init,
	/* event function */    seqg_event_editSseq_0_init,
	/* entry function */    seqg_entry_editSseq_0_init,
	/* exit function */     0,
	/* event mask array */  seqg_mask_editSseq_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "waitForCmnd",
	/* action function */   seqg_action_editSseq_0_waitForCmnd,
	/* event function */    seqg_event_editSseq_0_waitForCmnd,
	/* entry function */    seqg_entry_editSseq_0_waitForCmnd,
	/* exit function */     0,
	/* event mask array */  seqg_mask_editSseq_0_waitForCmnd,
	/* state options */     (0)
	},
	{
	/* state name */        "newRecordName",
	/* action function */   seqg_action_editSseq_0_newRecordName,
	/* event function */    seqg_event_editSseq_0_newRecordName,
	/* entry function */    seqg_entry_editSseq_0_newRecordName,
	/* exit function */     0,
	/* event mask array */  seqg_mask_editSseq_0_newRecordName,
	/* state options */     (0)
	},
	{
	/* state name */        "newCommand",
	/* action function */   seqg_action_editSseq_0_newCommand,
	/* event function */    seqg_event_editSseq_0_newCommand,
	/* entry function */    seqg_entry_editSseq_0_newCommand,
	/* exit function */     0,
	/* event mask array */  seqg_mask_editSseq_0_newCommand,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "editSseq",
	/* states */            seqg_states_editSseq,
	/* number of states */  4
	},
};

/* Program table (global) */
seqProgram editSseq = {
	/* magic number */      2002008,
	/* program name */      "editSseq",
	/* channels */          seqg_chans,
	/* num. channels */     73,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "P=xxx:, Q=ES:",
	/* num. event flags */  2,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};
# line 465 "../editSseq.st"

static int lineNum(char c) {
 int n;
 if (isdigit((int)c)) {
  if (c=='0') {
   n = 9;
  } else {
   n = c-'1';
  }
 } else if (toupper((int)c) == 'A') {
  n = 9;
 } else {
  n = 10;
 }
 return(n);
}
static char fieldChars[10] = {'1', '2', '3', '4', '5', '6', '7', '8', '9', 'A'};
static char fieldChar(int n) {
 char c;
 if (n>=0 && n<10) {
  c = fieldChars[n];
 } else {
  c = '?';
 }
 return(c);
}

static char fieldCharCheck(char c) {
 if (c=='0' || c=='a') c = 'A';
 return(c);
}




static int reconcilePVs(SS_ID ssId, struct UserVar *pVar,
 char *pattern, string *PV, int *PVIndex, char c_dest) {
 int i;

 for (i=0; i<10; i++) {
  if (strstr(PV[i], pattern) != 0) {
   PV[i][strlen(pattern)-1] = c_dest;
   if (c_dest != '*') {
    seq_pvPut(ssId, PVIndex[i], 0);
   }
  }
 }
 return(0);
}



/* Register sequencer commands and program */
#include "epicsExport.h"
static void editSseqRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&editSseq);
}
epicsExportRegistrar(editSseqRegistrar);
